### ISSUE TITLE
The link to the OSeMOSYS reference is not working

### ISSUE THREAD

**Issue by AgnesBelt** [sei-international/NemoMod.jl#2]
In the README file, under the Licensing and Attribution section, the link behind the OSeMOSYS name is not working.
Suggest to add link to the related GitHub repository: [https://github.com/OSeMOSYS/OSeMOSYS](url)

**Comment by jwveysey** [comment]
Thanks for bringing this to our attention!  I've corrected the link.

**Comment by AgnesBelt** [comment]
Thanks for correct this so quickly!
