### ISSUE TITLE
Data source for predicted future energy demand and renewable supply

### ISSUE THREAD

**Issue by freemin7** [sei-international/NemoMod.jl#5]
I was made aware of this package https://github.com/niclasmattsson/GlobalEnergyGIS . Adding support for files generated by this project as a data source might be interesting.

**Comment by jwveysey** [comment]
That package is interesting, and it looks like it provides some of the same functionality as another tool our team have been exploring, [RESkit](https://github.com/FZJ-IEK3-VSA/RESKit). However, given the other NEMO enhancements we're working on at the moment, I don't think we can commit to adding support for GlobalEnergyGIS files in the near term. This said, I'd be happy to take a pull request for a function to load GlobalEnergyGIS files - into a NEMO database or LEAP. Let me know if you're interested!
