### ISSUE TITLE
Remove solver dependency in the main module

### ISSUE THREAD

**Issue by freemin7** [sei-international/NemoMod.jl#6]
The only place where NemoMod uses GLPK is here https://github.com/sei-international/NemoMod.jl/blob/28595d9c94411d4917c60f4e43b1658dd54b615a/src/NemoMod.jl

This code is obviously dummy code and if removed only the test suite depends on particular solvers.

**Comment by jwveysey** [comment]
Yes, good catch.  This is an artifact from an earlier version, and I'll remove it in the next release.
