### ISSUE TITLE
Installing NEMO for Julia

### ISSUE THREAD

**Issue by ElenaNtm** [sei-international/NemoMod.jl#8]
Hello!
I want to install NEMO on a Julia editor, although I have read through the documentation I did not find clear instructions of how to download the package. Please understand the fact that I am a Python user and have no previous experience with Julia, apart from that I am also new to the world of Energy and how many things work. 
Thank you for your patience and I hope to get and answer to my question.

**Comment by jwveysey** [comment]
Hi, thanks for your interest in NEMO. If you're using the Julia REPL, you can download the latest version of the package by switching to package management mode (type `]`) and using this command:

`add https://github.com/sei-international/NemoMod.jl`

This is shown in [the part of the documentation on installing NEMO from GitHub](https://sei-international.github.io/NemoMod.jl/stable/installation/#github_installation), where you can also find information about downloading a specific version of NEMO.

Alternatively, if you're not in the REPL's package management mode, you can run Julia commands like these to download the latest version:

`using Pkg`
`Pkg.add(url="https://github.com/sei-international/NemoMod.jl")`
